/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package robotmotionplanner;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;
import java.awt.geom.Rectangle2D;
import javax.swing.JPanel;

/**
 *
 * @author Brian
 */
public class Interface extends javax.swing.JFrame {
    
    Point box1 = new Point(20,20);
    int box1_size = 200;
    Point box2 = new Point(300,100);
    int box2_size = 150;
    Point box3 = new Point(150,300);
    int box3_size = 100;
    
    int prevx;
    int prevy;
    boolean selectedBox1 = false;
    boolean selectedBox2 = false;
    boolean selectedBox3 = false;
    
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RobotFrame = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RobotFrame = new RobotWorkspace();
        RobotFrame.setBackground(new java.awt.Color(255, 255, 255));
        RobotFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RobotFrame.setPreferredSize(new java.awt.Dimension(500, 500));
        RobotFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                RobotFrameMouseReleased(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RobotFrameMousePressed(evt);
            }
        });

        javax.swing.GroupLayout RobotFrameLayout = new javax.swing.GroupLayout(RobotFrame);
        RobotFrame.setLayout(RobotFrameLayout);
        RobotFrameLayout.setHorizontalGroup(
            RobotFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        RobotFrameLayout.setVerticalGroup(
            RobotFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RobotFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RobotFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RobotFrameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RobotFrameMousePressed
        prevx = evt.getX();
        prevy = evt.getY();
        
        if(evt.getX() > box1.x && evt.getX() < box1.x+box1_size && evt.getY() > box1.y && evt.getY() < box1.y+box1_size)
            selectedBox1 = true;
        else if(evt.getX() > box2.x && evt.getX() < box2.x+box2_size && evt.getY() > box2.y && evt.getY() < box2.y+box2_size)
            selectedBox2 = true;
        else if(evt.getX() > box3.x && evt.getX() < box3.x+box2_size && evt.getY() > box3.y && evt.getY() < box3.y+box2_size)
            selectedBox3 = true;
    }//GEN-LAST:event_RobotFrameMousePressed

    private void RobotFrameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RobotFrameMouseReleased
        selectedBox1 = false;
        selectedBox2 = false;
        selectedBox3 = false;
    }//GEN-LAST:event_RobotFrameMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RobotFrame;
    // End of variables declaration//GEN-END:variables

    class RobotWorkspace extends JPanel implements MouseMotionListener{
        
        
        
        
        public RobotWorkspace(){
            addMouseMotionListener(this);
        }
        
        @Override
        public void paintComponent(Graphics g){
            super.paintComponent(g);
            Graphics2D g2 = (Graphics2D)g;
            
            g2.setPaint(Color.red);
            g2.fill(new Rectangle2D.Double(box1.x,box1.y,box1_size,box1_size));
            
            g2.setPaint(Color.blue);
            g2.fill(new Rectangle2D.Double(box2.x,box2.y,box2_size,box2_size));
            
            g2.setPaint(Color.green);
            g2.fill(new Rectangle2D.Double(box3.x,box3.y,box3_size,box3_size));
        }

        @Override
        public void mouseDragged(MouseEvent e) {
            
            if(selectedBox1){
                if(box1.x+(e.getX()-prevx)+box1_size <= this.getWidth() && box1.y+(e.getY()-prevy)+box1_size <= this.getHeight() && box1.x+(e.getX()-prevx) >= 0 && box1.y+(e.getY()-prevy) >= 0){
                    box1.x = box1.x+(e.getX()-prevx);
                    box1.y = box1.y+(e.getY()-prevy);
                }
            }
            else if(selectedBox2){
                if(box2.x+(e.getX()-prevx)+box2_size <= this.getWidth() && box2.y+(e.getY()-prevy)+box2_size <= this.getHeight() && box2.x+(e.getX()-prevx) >= 0 && box2.y+(e.getY()-prevy) >= 0){
                    box2.x = box2.x+(e.getX()-prevx);
                    box2.y = box2.y+(e.getY()-prevy);
                }
            }
            else if(selectedBox3){
                if(box3.x+(e.getX()-prevx)+box3_size <= this.getWidth() && box3.y+(e.getY()-prevy)+box3_size <= this.getHeight() && box3.x+(e.getX()-prevx) >= 0 && box3.y+(e.getY()-prevy) >= 0){
                    box3.x = box3.x+(e.getX()-prevx);
                    box3.y = box3.y+(e.getY()-prevy);
                }
            }
            else
                System.out.println();
                        
            this.repaint();
            
            prevx = e.getX();
            prevy = e.getY();
        }

        @Override
        public void mouseMoved(MouseEvent e) {
            
        }

        
        
    }
    
}
